Color mapping of tensors correction
SCIInstitute/scirun.pages pull request #16
Opened 2019-02-15 21:22 UTC by RubioJr9

Color mapping for tensors is based off magnitude of eigenvalues, not just the primary eigenvalue.

2019-02-15 21:26 UTC, dcwhite requested changes

2019-02-15 21:26 UTC, dcwhite commented on _includes/modules/ShowFieldGlyphs.md
> +The field in the first input port holds the data that is to be visualized. By default is will be displayed using the the default color, which is editable from the GUI If there is a color map attached
```suggestion
The field in the first input port holds the data that is to be visualized. By default is will be displayed using the the default color, which is editable from the GUI If there is a color map attached to the second input port, then the data can be used as an index into the color map, and the glyph is rendered with appropriate colors. In addition, the data itself can be converted into a color. **Scalar** data creates a gray scale mapping, **vector** data (normalized) creates RGB colors, and the **principle eigenvector** (normalized) of tensor data also creates RGB colors. For tensors, the vector magnitude of the three eigenvalues is used as the index into the color map. The absolute value of vector x, y, z components are used to generate RGB color components:
```

2019-02-15 21:26 UTC, dcwhite commented on _includes/modules/ShowFieldGlyphs.md
> +The field in the first input port holds the data that is to be visualized. By default is will be displayed using the the default color, which is editable from the GUI If there is a color map attached
Fix typo

2019-02-15 21:26 UTC, jessdtate reviewed
Does this description match what the colormap lookup currently does, or the way that it will be?

2019-03-13 19:39 UTC, dcwhite commented
Not sure how to fix the build error. I'll rerun it...

2019-05-13 19:08 UTC, RubioJr9 commented
Dan, could you rerun the Travis build?

2019-05-23 16:15 UTC, dcwhite approved these changes

2019-05-23 16:28 UTC, merged