Show And Edit Dipoles
SCIInstitute/scirun.pages pull request #17
Opened 2019-07-01 18:41 UTC by RubioJr9

- Added new doc for ShowAndEditDipoles module.
- Fixed spacing on ShowFieldGlyphs.

2019-08-26 20:59 UTC, jessdtate requested changes

2019-08-26 20:59 UTC, jessdtate commented on modules/ShowAndEditDiples.md
> +---
This content should go in the `_includes/modules` folder.  This file should be a link to the other.

2019-08-26 22:15 UTC, dcwhite commented on modules/ShowAndEditDiples.md
> +---
@RubioJr9 Please fix

2019-09-20 16:24 UTC, dcwhite commented
@jessdtate Can this be merged now?

2019-09-20 16:25 UTC, jessdtate approved these changes

2019-09-20 16:25 UTC, merged